### ISSUE TITLE
Noticed an error marked on the Variable CustomFiscalRawDays. 

### ISSUE THREAD

**Issue by DeBertsch** [sql-bi/DaxDateTemplate#17]
I noticed an error showing on CustomFiscalRawDays...it doesn't show a problem now but was wondering if it would be resolved.

**Comment by marcosqlbi** [comment]
Power BI has a bug displaying an error in a line that in reality is a valid DAX code. I already submitted it as a bug to Microsoft, hopefully they will fix it..
