### ISSUE TITLE
Comment - Future year

### ISSUE THREAD

**Issue by DeBertsch** [sql-bi/DaxDateTemplate#18]
Var TodayReference = VAR CurrentDate = TODAY()
Return 
 Date(Year(CurrentDate)+2,Month(CurrentDate),DAY(CurrentDate))
VAR LastYear = YEAR ( TodayReference )

I have replace for future years as people will use for predictive.  There may be a better way to code it but I am just slightly better than novice.  May be something to think about changing.

**Comment by marcosqlbi** [comment]
The entire initial section defines variable that are parameters for the date generation. These settings are supposed to be customized according to specific requirements. I would not apply further changes to the standard template, though. Thanks!
