### ISSUE TITLE
Future Year

### ISSUE THREAD

**Issue by OldManToy** [sql-bi/DaxDateTemplate#22]
Hi, I've tried to amend the initial parameters to enables the time period to end 31 March 2020 (as the end of this current fiscal year) but I just can't get it to work - I'm probably doing it wrongly as I'm an utter novice.

So, can someone be really kind and let me have the exact text to paste into the query to achieve this. My table currently ends in December 2019, so three month's short for my needs!

Thanks! and fingers crossed...

**Comment by marcosqlbi** [comment]
You should change the setting CalendarRange according to your needs. Probably you need this:

VAR CalendarRange = "FiscalGregorian"

You can find the possible values in the comments included in the DAX code.
