### ISSUE TITLE
Using Date table in existing report

### ISSUE THREAD

**Issue by vgeldbr** [sql-bi/DaxDateTemplate#25]
Is there any way of using the Date table from the template in an existing Power BI report? Copying the table loses the formatting of the table including the sort orders for the various columns. Unfortunately I'm not in a position to start the entire report from scratch in the Date template.

**Comment by marcosqlbi** [comment]
You do not have a supported way to do that. If you read in the comments of https://www.sqlbi.com/tools/dax-date-template/ there is a description of a technique that actually works that I copy here for your convenience:

1) Save your PBIX as a template (PBIT)
2) Open your PBIT using Tabular Editor (A)
3) Open the DAX Date Template in another window of Tabular Editor (B)
4) Select the Date table in (B) and Copy it in the clipboard
5) Select the Date table in (A) and Paste - confirming you want to replace the existing table

This works if you have the same column names for the key of the relationship and the same column names if you already used the Date table in some report.
Remember, it's unsupported...
