### ISSUE TITLE
Calendar only populating up to Dec. 28, 2019

### ISSUE THREAD

**Issue by egarstad** [sql-bi/DaxDateTemplate#26]
When setting 

FiscalCalendarFirstMonth = 1
and
CalendarRange = "Calendar"

the calendar only creates dates up until Dec. 28, 2019. Using any other month for FiscalCalendarFirstMonth the calendar will populate up to Dec. 31, 2019.

**Comment by marcosqlbi** [comment]
Can you send me the complete configuration? I want to reproduce and it is probably related to other settings.

**Comment by egarstad** [comment]
Hi Marco,

The issue is reproducible using the template file V1.11 that is available for download from GitHub. Simply changing FiscalCalendarFirstMonth from 7 to 1 (with no other changes) will cause the issue to happen.

**Comment by marcosqlbi** [comment]
It seems the issue is caused by the CompleteCalendarExpanded variable – this is the right assignment:

VAR CompleteCalendarExpanded =
    NATURALLEFTOUTERJOIN(
        FiscalStandardGregorian,
        NATURALLEFTOUTERJOIN ( CalendarStandardGregorian, FiscalWeeks )
    )

I will publish an updated version soon.
Thanks!

**Comment by marcosqlbi** [comment]
Version 1.12 published including this fix
