### ISSUE TITLE
[FW StartOfYear] [FW EndOfYear] lines 701-702

### ISSUE THREAD

**Issue by P-Blackburn** [sql-bi/DaxDateTemplate#30]
I am perhaps missing something but I have downloaded the PBIT and the PBX and when I look in the  Date Configuration around lines 701-702  I'm seeing that [FW StartOfYear] cannot be found etc...

![image](https://user-images.githubusercontent.com/47189653/73327686-d2d0c100-424e-11ea-8500-d3757047ce8d.png)

Is there something I should be setting somewhere to overcome this?

**Comment by marcosqlbi** [comment]
The error you see in the editor is a bug in IntelliSense in Power BI. That line is a valid DAX code that generates a valid table.
IntelliSense in Power BI has several other small bugs. If the code is accepted by the editor and doesn't show any error at the bottom of the editor with a yellow background, it's valid DAX code. If you see the error message, that error is accurate and stops the execution of the DAX code.
You can go ahead... and perhaps ask to Microsoft to fix the bug! :)
