### ISSUE TITLE
Add a Working Day Number for the month

### ISSUE THREAD

**Issue by marcl1** [sql-bi/DaxDateTemplate#34]
Hi,

based on the column "Day type" and on an internet feed 
https://community.powerbi.com/t5/Desktop/Calculate-the-current-business-day-number-in-the-month/m-p/561508#M264882
I've created the column Working Day Number

Would it be integrated directly in the table and programmed perfectly, it would be perfect !
thx in advance

**Comment by marcosqlbi** [comment]
The Working Day is already available in the column "IsWorkingDay" and it is populated according to the configuration you set in the table.
Why do you need the working day number as a calculated column?

**Comment by marcl1** [comment]
Dear Marco,

Thx a lot for your quick answer !
Hope all is fine with you in this Corona period and that you are safely in home office 😊

(please keep confidential these data)

I’m working in a business where our sales and other activities are usually during the weekdays.
As we compare usually the current year and the previous year, it would be good to compare WD1 of this year with the WD1 of previous year, as it should be in the bottom view (and I fear that I’ve a mistake somewhere), … Until now the Corona hasn’t hurt too bad, but now we start to notice a strong decline in many of our countries…

Now if you suggest smth wiser, I’m more than happy to learn !

PS: by the way I’ve asked my boss to take part in one of your advanced DAX sessions, he postponed it, and currently the situation is not favorable.


[cid:image001.png@01D60299.FD3B92C0]

[cid:image003.png@01D6029B.134AE470]

Mit freundlichen Grüßen / Best regards / Salutations
Dr. Laurent Marc
Senior Specialist Business Controlling

Phone: +49 62160 44662, Mobile:  +49 1525 4912784, Email: laurent.marc@basf.com
Postal Address:   BASF Construction Solutions GmbH,  R64-5,  Salzachstr. 17,  68199  Mannheim,  Germany
[cid:image002.png@01D60299.FD3B92C0]
BASF Construction Solutions GmbH, Registered Office: 83308 Trostberg, Germany
Companies' Register: Amtsgericht Traunstein, HRB 10261
Managing Directors: Philipp Kley, Erich Lackner
www.basf-construction-solutions.com




De : Marco Russo <notifications@github.com>
Envoyé : Wednesday, March 25, 2020 09:56
À : sql-bi/DaxDateTemplate <DaxDateTemplate@noreply.github.com>
Cc : Laurent Marc <laurent.marc@basf.com>; Author <author@noreply.github.com>
Objet : Re: [sql-bi/DaxDateTemplate] Add a Working Day Number for the month (#34)


The Working Day is already available in the column "IsWorkingDay" and it is populated according to the configuration you set in the table.
Why do you need the working day number as a calculated column?

**Comment by marcosqlbi** [comment]
This section is public - please remove any sensitive data immediately thanks!

**Comment by marcl1** [comment]
I’m working in a business where our sales and other activities are usually during the weekdays.
As we compare usually the current year and the previous year, it would be good to compare WD1 of this year with the WD1 of previous year, and the same for the following days...

**Comment by marcosqlbi** [comment]
I suggest you creating a calculated column counting the working days before the current date to populate the column.
