### ISSUE TITLE
5-4-4 not generating correct quarters

### ISSUE THREAD

**Issue by securus777** [sql-bi/DaxDateTemplate#36]
Good Morning,

Seems like when 5-4-4 is used the weeks are not falling into the correct quarters. For instance in the attached image you can see that 3/29 and 3/30 should show in Q2 as they are in week 14.
![image](https://user-images.githubusercontent.com/28575064/78906296-2df01280-7a4d-11ea-8d2c-7609b9a8cae1.png)

Though I could be wrong on the config (544 is selected).

Thanks

**Comment by marcosqlbi** [comment]
Use FW columns when you use Fiscal Week calendar - the FW quarter column is correct.
I suggest to remove the columns you don't need by removing the last few lines of the DAX Code, so you only have the calendar really needed, either Fiscal (based on months) or FW (Fiscal based on weeks).
