### ISSUE TITLE
Cannot find name [FW StartOfYear]; [FW EndOfYear] 

### ISSUE THREAD

**Issue by Dnich88** [sql-bi/DaxDateTemplate#38]
Hi,
I get the red lines under this part of the code.
VAR CustomFiscalRawDays =
    GENERATE ( FiscalPeriods; CALENDAR( [FW StartOfYear]; [FW EndOfYear] ) )
It is in both the pbix and the pbit.

**Comment by marcosqlbi** [comment]
It is a bug in the Power BI Editor - as long as the code works, it is not a syntax error.
If you see a message error at the bottom of the DAX editor, then there is a problem in the DAX code.
