### ISSUE TITLE
Both the template & report files aren't opening.

### ISSUE THREAD

**Issue by pratapladhani** [sql-bi/DaxDateTemplate#40]
I downloaded the latest "DAX Date Template.pbit" and "DAX Date Template.pbix" files, but both of them aren't opening up in my Power BI Desktop app. The error is : Unable to open template - DAX Date Template.pbit is corrupt or an invalid report file.

I am on the following version of the Power BI Desktop application, which was updated 2 days ago on 8/14/2020. 

Release:
August 2020

Product Version:
2.84.701.0 (20.08) (x64)

OS Version:
Microsoft Windows NT 10.0.19041.0 (x64 en-US)

CLR Version:
4.7 or later [Release Number = 528372]

Feedback Type:
Frown (Error)

**Comment by pratapladhani** [comment]
Please ignore this. I had accidentally downloaded the wrong files.

**Comment by marcosqlbi** [comment]
No problems - thanks for closing the loop quickly.
