### ISSUE TITLE
Relative Offsets are backwards

### ISSUE THREAD

**Issue by ghost** [sql-bi/DaxDateTemplate#41]
It looks like the Calendar RelativeWeekPos (and Month, Quarter, Year) are backwards. The documentation says negative values should be in the past and positive values are in the future relative to the TodayReference. At line# 822, if you flip the calculation from 

`VAR RelativeWeekPos =   CurrentWeekPos - YearWeekNumber` 

to `VAR RelativeWeekPos =  YearWeekNumber - CurrentWeekPos` it will work.

**Comment by marcosqlbi** [comment]
Fixed in v1.15, thanks!
