### ISSUE TITLE
Question: Reference for creating heirarchies

### ISSUE THREAD

**Issue by skorvek** [sql-bi/DaxDateTemplate#45]
First of all: thank you for this. You are an authoritative reference for all things PowerBI and one of the first people I look for if I'm trying to fix/understand the "right way" to do something rather than trying other hack-y solutions to a thorny problem.

I read through the documentation and cannot find anything referencing the hierarchies you created.  You have renamed the elements so I'm not 100% sure of the underlying references.  Is it as simple as (for example) Calendar Quarters is composed of Calendar Year/Calendar Quarter/Calendar Month? Or might you have used "Calendar Month Year" or something else? 

Thanks. I cannot use the template directly- I have other existing PBIX to add this to and it's a lot less work to recreate the sorting/naming/hiding than to start over with everything else- plus I'd like to understand.

**Comment by marcosqlbi** [comment]
I didn't write documentation for that.
User hierarchies don't affect the DAX calculation, so you can choose your own or just look at the existing one peeking the content using another instance of Power BI or by opening the file with Tabular Editor.
