### ISSUE TITLE
Weeknumbers during Yearchange 2020-2021

### ISSUE THREAD

**Issue by MvanderPut** [sql-bi/DaxDateTemplate#49]
The Calendar Week Year and Calendar RelativeWeekPos were wrong calculated for 2021.
It should be: 1-3 January are week 53 and Week 1 of 2021 start at January 4th
Now Week 1 is January 1st-3th and Week 2 starts at January 4th.

How can ths be fixed?

**Comment by marcosqlbi** [comment]
The Calendar prefixed columns strictly follow the Gregorian Calendar.
You should use the FW prefixed columns to get the week numbers you want.
