### ISSUE TITLE
Duplicate of Anzac Day /Australia day in 2011

### ISSUE THREAD

**Issue by BVMather** [sql-bi/DaxDateTemplate#5]
If you choose IsoCountryHolidays = "AU"  then the date table fails to load.

You get an error that the primary date key must contain unique values. 

Troubleshooting I see that Anzac Day and Easter Sunday fall on the same day in 2011.  You would need to calculate the Easter holidays days first, and continue to offset the 'normal' holiday by +1 until you reach a non-Easter holiday working day.

I'm trying to figure out the required change, possibly to SubstituteHolidayOffset.

**Comment by BVMather** [comment]
I've checked some others and you get the same problem for: 
> Ascension Day / Labour Day in Belgium in 2008.
> Ascension Day / Liberation Day in Netherlands in 2005 & 2016

There will need to be a check does a particular holidaydate fall on any of the dates generated from a table of all the holidays that are Easter-offset holidays

**Comment by marcosqlbi** [comment]
Fixed by version 1.0.1
