### ISSUE TITLE
WEEKNUM compatibility with ISO 8601

### ISSUE THREAD

**Issue by sfeldmannDE** [sql-bi/DaxDateTemplate#50]
I'm using the DaxDate Template v.1.14 and I guess there is a problem with the week number. Related to ISO 8601 the first three days in January 2021 are week number 53 where as in the DaxDateTemplate the week number starts with 1. 

![WEEKNUM_v1-14](https://user-images.githubusercontent.com/77271979/104169518-ff4e0080-53ff-11eb-9a85-6c59025e5694.png)

**Comment by marcosqlbi** [comment]
The ISO standard is implemented in FW prefixed columns. Check comments to properly setup parameters.
