### ISSUE TITLE
Issues with leap-year

### ISSUE THREAD

**Issue by mazhar-debug** [sql-bi/DaxDateTemplate#51]
Hi,

So last year was a leap year, and now I'm having some issues with the generated Date-table from SQLBI.

The calendar should look like this, for 2021:
![attachment1](https://user-images.githubusercontent.com/54494070/104891873-c5d24380-5971-11eb-9d45-11c2253b8ab9.png)

This is how it looks, however, when using your Date-table:
![image](https://user-images.githubusercontent.com/54494070/104891971-e4d0d580-5971-11eb-8f41-95be5cd41c76.png)

So W53 should include the first three days of 2021, but it doesn't, causing every week after to shift to the next week.

**Comment by marcosqlbi** [comment]
For weekly-base calendar you should use the FW prefixed columns.
