### ISSUE TITLE
RealtiveWeek Position 

### ISSUE THREAD

**Issue by ColinEyres** [sql-bi/DaxDateTemplate#52]
Hi Guys,

I noticed other sites say current calendar week is 5, yet the SQL BI Date says current week is 6, which starts Feb 7 - 13, 2021. 

The relative week positions correctly shows 0   for days Jan 31 to Feb 6, 2021. 

This was working before really well, but now it doesn't.  Last year was a leap year. 

I tried getting the latest version of your template - same issue. 

Looking at the cut offs between 2020 and 2021, I can see 2 days as Week 1 when it should be week 53. 
![image](https://user-images.githubusercontent.com/78507068/106812508-05b15000-662d-11eb-9b1d-b0f34e018048.png)

 
![Screenshot 2021-02-03 133238 PNG](https://user-images.githubusercontent.com/78507068/106805793-5bcdc580-6624-11eb-8203-64024eab337e.jpg)

![image](https://user-images.githubusercontent.com/78507068/106808739-009dd200-6628-11eb-993c-8ef31c8f7f82.png)

**Comment by marcosqlbi** [comment]
You shouls use the FW prefixed columns, which follow the fiscal week structure.

**Comment by ColinEyres** [comment]
I see. Thanks for the fast response Marco!
