### ISSUE TITLE
[FW EndOfYear] not found

### ISSUE THREAD

**Issue by kemherar** [sql-bi/DaxDateTemplate#53]
Missing variable or reference after copy and paste from template pbix

![screenshot](https://user-images.githubusercontent.com/79166021/108108070-1c5c9b80-705e-11eb-9178-949c73909f0e.png)

**Comment by marcosqlbi** [comment]
The DAX code is valid, it's a bug of the Power BI editor - please, submit it to Microsoft, it has been there for years and they still didn't fix it!

**Comment by kemherar** [comment]
> The DAX code is valid, it's a bug of the Power BI editor - please, submit it to Microsoft, it has been there for years and they still didn't fix it!

But then, there is no solution or bypass to make it work on my side until they fix it?

**Comment by marcosqlbi** [comment]
As I said, the code works - it's just the editor showing an error that is not an error. It is a non-blocking-issue (as Microsoft says).
