### ISSUE TITLE
Need to add Juneteenth to US Holidays

### ISSUE THREAD

**Issue by HymieHo** [sql-bi/DaxDateTemplate#57]
Juneteenth National Independence Day 

https://en.wikipedia.org/wiki/Juneteenth#Legal_observance
"According to the bill, federal government employees will now get to take the day off every year on June 19, or should the date fall on a Saturday or Sunday, they will get the Monday or Friday closest to the Saturday or Sunday on which the date falls."

**Comment by HymieHo** [comment]
I created a PR with the changes applied to the PBIX. The DAX is attached to this comment.

[DAX Date Template.txt](https://github.com/sql-bi/DaxDateTemplate/files/6744267/DAX.Date.Template.txt)

**Comment by marcosqlbi** [comment]
I implemented it in v1.15 through a more generic technique that can be applied to any similar holiday. The replaced holiday appears as "(in lieu of Juneteenth)" as for other similar holiday replacements.

**Comment by HymieHo** [comment]
I knew there was a more elegant solution--thanks. The only issue is that Juneteenth started in 2021 yet this code will show Juneteenth as a holiday in any year.  Do we need to add a parameter to HolidayParameters for "start year", -1 for all? As time marches on it will be less important, but especially for 2022 it will be noticed in all "prior year" measures that take working days into account.

**Comment by marcosqlbi** [comment]
This is now fixed in 1.18. Thanks!
