### ISSUE TITLE
Austrian (AT) holidays did not make it into Version 1.15

### ISSUE THREAD

**Issue by MEhrenmueller** [sql-bi/DaxDateTemplate#67]
Despite the announcement, Austrian (AT) holidays did not make it into Version 1.15.
At least, I cannot find a reference to "AT" in the section beginning at line 113.

**Comment by marcosqlbi** [comment]
It seems I missed the alphabetical order! :) AT is just after AU. I'll fix it in the next release, but Austria is there (look for AT after AU).

**Comment by MEhrenmueller** [comment]
I cannot confirm ...
After "AU" for me "DE" is listed next.

![image](https://user-images.githubusercontent.com/22891480/143835313-4b094cff-6346-46cc-b8e1-c50449f091c9.png)

**Comment by marcosqlbi** [comment]
Did you get the latest version? I just downloaded it and I changed completely the order.

**Comment by MEhrenmueller** [comment]
My bad. 
I thought that I downloaded the latest version. At least it downloaded a file named DaxDateTemplate-1.15.zip, but the content shows timestamps for 2020-02-14 ...
Now I tried again and downloaded file DaxDateTemplate-master.zip, which contains files with updated timestamps and "AT" as well.

All good! Thanks for your fast response! And _mille gracie_ for including the Austrian holidays!

**Comment by marcosqlbi** [comment]
Probably I understood - I made a mess with tags, now I released again as 1.15a (I cannot delete the 1.15 tag) but the only release is now 1.15.
So also the repo is fixed now.
Thanks for reporting it!!
