### ISSUE TITLE
DirectQuery mode does not work with PBIX files created from the template

### ISSUE THREAD

**Issue by zsomborzsuffa** [sql-bi/DaxDateTemplate#8]
When a new PBIX file is created from the template DirectQuery connections cannot be added to the model because the Date table that is created is considered as being an imported dataset and in the model cannot be mixed DQ and Imported datasets.

The error message that is generated after adding a direct query connection is: 
Failed to save modifications to the server. Error returned: 'Partitions that contain a full dataset (not sampled data) have to be configured for DirectQuery and Full DataViews, or use Import query mode to retrieve data. This model appears to have partitions that are non-compliant. Please check partition configuration.
'.

What would be the way to use the template with DQ?

**Comment by marcosqlbi** [comment]
Calculated tables are not supported in DirectQuery, so you have to create a Date table in your data source in SQL.
